"""changed task description column type to Text

Revision ID: 646201c43f26
Revises: 577b33e86d32
Create Date: 2026-03-25 04:02:59.036129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646201c43f26'
down_revision: Union[str, Sequence[str], None] = '577b33e86d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    connection = op.get_bind()

    too_long_exists = connection.execute(
        sa.text(
            """
            SELECT 1
            FROM tasks
            WHERE description IS NOT NULL
              AND char_length(description) > 200
            LIMIT 1
            """
        )
    ).scalar()

    if too_long_exists:
        raise RuntimeError(
            "Cannot downgrade tasks.description to VARCHAR(200): "
            "found values longer than 200 characters."
        )

    op.alter_column(
        "tasks",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=200),
        existing_nullable=True,
    )
